version: '3.9'

services:
  DB-udagram:
    image: postgres
    container_name: DB-udagram
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - 'DB-udagram:/var/lib/postgresql/data'

volumes:
  DB-udagram: